@startuml
'https://plantuml.com/object-diagram

object "<u>testDocument : Document</u>" as td{
    CHARACTERS : Character[*]
}
object "<u>propertiesFactory : CharacterPropertiesFactory</u>" as pf{
    FLYWEIGHTS : Map<String, CharacterProperties>
}
object "<u>H : Character</u>" as c1{
    character = 'H'
}
object "<u>e : Character</u>" as c2{
    character = 'e'
}
object "<u>l : Character</u>" as c3{
    character = 'l'
}
object "<u>l : Character</u>" as c4{
    character = 'l'
}
object "<u>o : Character</u>" as c5{
    character = 'o'
}
object "<u>W : Character</u>" as c6{
    character = 'W'
}
object "<u>o : Character</u>" as c7{
    character = 'o'
}
object "<u>r : Character</u>" as c8{
    character = 'r'
}
object "<u>l : Character</u>" as c9{
    character = 'l'
}
object "<u>d : Character</u>" as c10{
    character = 'd'
}
object "<u>C : Character</u>" as c11{
    character = 'C'
}
object "<u>S : Character</u>" as c12{
    character = 'S'
}
object "<u>5 : Character</u>" as c13{
    character = '5'
}
object "<u>8 : Character</u>" as c14{
    character = '8'
}
object "<u>0 : Character</u>" as c15{
    character = '0'
}
object "<u>0 : Character</u>" as c16{
    character = '0'
}

object "<u>ArialBlack16 : CharacterProperties</u>" as p1{
    FONT : "Arial"
    COLOR : "Black"
    SIZE : 16
}
object "<u>ArialBlack14 : CharacterProperties</u>" as p2{
    FONT : "Arial"
    COLOR : "Black"
    SIZE : 14
}
object "<u>VerdanaBlue18 : CharacterProperties</u>" as p3{
    FONT : "Verdana"
    COLOR : "Blue"
    SIZE : 18
}
object "<u>VerdanaRed12 : CharacterProperties</u>" as p4{
    FONT : "Verdana"
    COLOR : "Red"
    SIZE : 12
}

c1 o-- p1
c2 o-- p2
c3 o-- p2
c4 o-- p2
c5 o-- p2
c6 o-- p1
c7 o-- p2
c8 o-- p2
c9 o-- p2
c10 o-- p2

c11 o-- p3
c12 o-- p3
c13 o-- p4
c14 o-- p4
c15 o-- p4
c16 o-- p4

td *-- c1
td *-- c2
td *-- c3
td *-- c4
td *-- c5
td *-- c6
td *-- c7
td *-- c8
td *-- c9
td *-- c10
td *-- c11
td *-- c12
td *-- c13
td *-- c14
td *-- c15
td *-- c16

td *-- pf
'this line is used to layout the diagram
td -up[hidden]- pf

pf *-- p1
pf *-- p2
pf *-- p3
pf *-- p4

@enduml
